### ISSUE TITLE
Non ESPHome based RS485 interface

### ISSUE THREAD

**Issue by whizkidTRW** [gazoodle/CenturyVSPump#3]
Gazoodle, since I don’t have good enough Wi-Fi near my pool pump, I bought a modbus capable Wi-Fi & Ethernet interface (below) so I can do a wired connection. How can I use this with your code? I’m very new to Home Assistant, thanks in advance!

https://a.co/d/ivMZfGj

**Comment by gazoodle** [comment]
I'm not sure that device will support ESPHome firmware in which case this repo isn't going to really help you a great deal apart from pointers on how to actually drive the device.

Personally, I'd start by trying to get the pump physically wired up to the device, then use it's MQTT or Web interface to see what happens when you send it commands. For example, the modbus bytes `15:44:20:00:00:19:38:DB` should set the pump speed to 1600RPM, `15:43:20:50:EC` should tell the pump to run and `15:42:20:51:7C` should tell the pump to stop.
